services:
  migrations:
    container_name: tgvs-migrations
    image: ${DOCKER_REGISTRY-}tgvs-migrations
    build:
      context: .
      dockerfile: src/Tgvs/Dockerfile
      target: migrations
    depends_on:
        - sqlserver
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password_123